# 1️⃣ Build da aplicação
FROM node:22.15-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
# RUN npm ci
RUN npm i

COPY frontend/ .
RUN npm run build


# Imagem final com Nginx
FROM nginx:alpine AS runner

# Copia o build para o nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia configuração customizada do Nginx (opcional)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expondo porta
EXPOSE 80

# Comando padrão
CMD ["nginx", "-g", "daemon off;"]
