name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15

      - name: Instalar dependências
        # run: npm ci
        run: npm i

      - name: Rodar os testes
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub (opcional, se quiser usar registry privado)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Testar login no Docker
        run: docker info

      - name: Build imagem de produção
        run: docker build -f Dockerfile.prod -t minha-app:latest .

      # Se quiser mandar para Docker Hub
      # - name: Push imagem para Docker Hub
      #   run: docker tag minha-app:latest meu-usuario/minha-app:latest && docker push meu-usuario/minha-app:latest

      # Deploy para a Vercel via Vercel CLI
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
